"""option positions

Revision ID: 0b00be905952
Revises: 4a7fb3c995db
Create Date: 2026-07-31 16:02:25.815614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b00be905952'
down_revision: Union[str, None] = '4a7fb3c995db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('CALL', 'PUT', name='option_type', native_enum=False, length=32), nullable=False),
    sa.Column('strike', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('size', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('premium_paid', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'EXERCISED', 'EXPIRED', name='option_status', native_enum=False, length=32), nullable=False),
    sa.Column('payout', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('settle_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('strike > 0 AND size > 0 AND premium_paid >= 0', name='ck_options_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_options_open', 'option_positions', ['status', 'expiry'], unique=False)
    op.create_index('ix_options_user', 'option_positions', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_options_user', table_name='option_positions')
    op.drop_index('ix_options_open', table_name='option_positions')
    op.drop_table('option_positions')
    # ### end Alembic commands ###
