"""stop orders: trigger fields

Revision ID: 10245424834f
Revises: f5664f09a690
Create Date: 2026-07-23 16:09:54.480169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10245424834f'
down_revision: Union[str, None] = 'f5664f09a690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('trigger_price', sa.Numeric(precision=36, scale=18), nullable=True))
    op.add_column('orders', sa.Column('trigger_above', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Hand-written: the price/trigger CHECK constraints. Autogenerate does not diff CHECK text.
    op.drop_constraint("ck_orders_limit_has_price", "orders", type_="check")
    op.create_check_constraint(
        "ck_orders_limit_has_price", "orders",
        "(type IN ('MARKET', 'STOP_MARKET')) OR (price IS NOT NULL AND price > 0)",
    )
    op.create_check_constraint(
        "ck_orders_stop_has_trigger", "orders",
        "(type IN ('STOP_LIMIT', 'STOP_MARKET')) = (trigger_price IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint("ck_orders_stop_has_trigger", "orders", type_="check")
    op.drop_constraint("ck_orders_limit_has_price", "orders", type_="check")
    op.create_check_constraint(
        "ck_orders_limit_has_price", "orders",
        "(type = 'MARKET') OR (price IS NOT NULL AND price > 0)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'trigger_above')
    op.drop_column('orders', 'trigger_price')
    # ### end Alembic commands ###
