"""kyc applications

Revision ID: 192e61f1a623
Revises: b069b0e9a624
Create Date: 2026-07-30 11:55:47.864335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192e61f1a623'
down_revision: Union[str, None] = 'b069b0e9a624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED', 'REJECTED', name='kyc_status', native_enum=False, length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=56), nullable=False),
    sa.Column('id_type', sa.String(length=32), nullable=False),
    sa.Column('id_number', sa.String(length=64), nullable=False),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_applications')
    # ### end Alembic commands ###
