"""margin foundation

Revision ID: 252e82ce6616
Revises: 339788d51854
Create Date: 2026-07-28 15:37:25.237093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252e82ce6616'
down_revision: Union[str, None] = '339788d51854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Enum('CROSS', 'ISOLATED', name='margin_mode', native_enum=False, length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.Enum('CLASSIC', 'PRO', name='margin_tier', native_enum=False, length=32), nullable=False),
    sa.Column('max_leverage', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='margin_account_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(mode = 'CROSS' AND symbol IS NULL) OR (mode = 'ISOLATED' AND symbol IS NOT NULL)", name='ck_margin_accounts_symbol_by_mode'),
    sa.CheckConstraint('max_leverage >= 1', name='ck_margin_accounts_leverage'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_margin_cross', 'margin_accounts', ['user_id'], unique=True, postgresql_where=sa.text("mode = 'CROSS'"))
    op.create_index('uq_margin_isolated', 'margin_accounts', ['user_id', 'symbol'], unique=True, postgresql_where=sa.text("mode = 'ISOLATED'"))
    op.create_table('margin_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margin_account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REPAID', name='margin_loan_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('principal >= 0 AND accrued_interest >= 0 AND hourly_rate >= 0', name='ck_margin_loans_nonneg'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['margin_account_id'], ['margin_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_margin_loans_account', 'margin_loans', ['margin_account_id', 'status'], unique=False)
    op.create_index('ix_margin_loans_open', 'margin_loans', ['status', 'asset_id'], unique=False)
    op.add_column('accounts', sa.Column('wallet', sa.String(length=24), server_default='SPOT', nullable=False))
    op.drop_index(op.f('uq_accounts_system_asset_type'), table_name='accounts', postgresql_where='(user_id IS NULL)')
    op.create_index('uq_accounts_system_asset_type', 'accounts', ['asset_id', 'account_type', 'wallet'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('uq_accounts_user_asset_type'), table_name='accounts', postgresql_where='(user_id IS NOT NULL)')
    op.create_index('uq_accounts_user_asset_type', 'accounts', ['user_id', 'asset_id', 'account_type', 'wallet'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###

    # Hand-written: let the margin lending pool go negative alongside EXTERNAL/TDS.
    op.drop_constraint("ck_accounts_no_negative_user_balance", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_no_negative_user_balance", "accounts",
        "balance >= 0 OR account_type IN ('EXTERNAL', 'TDS_PAYABLE', 'MARGIN_BORROWED')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_accounts_no_negative_user_balance", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_no_negative_user_balance", "accounts",
        "balance >= 0 OR account_type IN ('EXTERNAL', 'TDS_PAYABLE')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_accounts_user_asset_type', table_name='accounts', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index(op.f('uq_accounts_user_asset_type'), 'accounts', ['user_id', 'asset_id', 'account_type'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.drop_index('uq_accounts_system_asset_type', table_name='accounts', postgresql_where=sa.text('user_id IS NULL'))
    op.create_index(op.f('uq_accounts_system_asset_type'), 'accounts', ['asset_id', 'account_type'], unique=True, postgresql_where='(user_id IS NULL)')
    op.drop_column('accounts', 'wallet')
    op.drop_index('ix_margin_loans_open', table_name='margin_loans')
    op.drop_index('ix_margin_loans_account', table_name='margin_loans')
    op.drop_table('margin_loans')
    op.drop_index('uq_margin_isolated', table_name='margin_accounts', postgresql_where=sa.text("mode = 'ISOLATED'"))
    op.drop_index('uq_margin_cross', table_name='margin_accounts', postgresql_where=sa.text("mode = 'CROSS'"))
    op.drop_table('margin_accounts')
    # ### end Alembic commands ###
