"""add trades table and orders.filled_quantity

Revision ID: 28837cae7296
Revises: d2310868c178
Create Date: 2026-07-23 15:53:09.380843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28837cae7296'
down_revision: Union[str, None] = 'd2310868c178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('taker_order_id', sa.BigInteger(), nullable=False),
    sa.Column('maker_order_id', sa.BigInteger(), nullable=False),
    sa.Column('taker_side', sa.String(length=4), nullable=False),
    sa.Column('buyer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("taker_side IN ('BUY','SELL')", name='ck_trade_taker_side'),
    sa.CheckConstraint('price > 0', name='ck_trade_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_trade_quantity_positive'),
    sa.CheckConstraint('taker_order_id <> maker_order_id', name='ck_trade_distinct_orders'),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.order_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.order_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_trades_buyer_user_id'), 'trades', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_trades_maker_order_id'), 'trades', ['maker_order_id'], unique=False)
    op.create_index('ix_trades_pair_created', 'trades', ['pair', 'created_at'], unique=False)
    op.create_index(op.f('ix_trades_seller_user_id'), 'trades', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_trades_taker_order_id'), 'trades', ['taker_order_id'], unique=False)
    op.add_column('orders', sa.Column('filled_quantity', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'filled_quantity')
    op.drop_index(op.f('ix_trades_taker_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_seller_user_id'), table_name='trades')
    op.drop_index('ix_trades_pair_created', table_name='trades')
    op.drop_index(op.f('ix_trades_maker_order_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_buyer_user_id'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
