"""launchpad: tokens, offerings, amm pools

Revision ID: 2dc0d44f4e42
Revises: f428ba7489a9
Create Date: 2026-08-04 17:34:21.298650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc0d44f4e42'
down_revision: Union[str, None] = 'f428ba7489a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amm_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset_id', sa.Integer(), nullable=False),
    sa.Column('reserve_token', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('reserve_quote', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('lp_supply', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fee_bps >= 0 AND fee_bps < 10000', name='ck_amm_pools_fee_range'),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['token_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_asset_id', 'quote_asset_id', name='uq_amm_pools_pair')
    )
    op.create_table('launched_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('total_supply', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('target_audience', sa.String(length=300), nullable=False),
    sa.Column('offering_type', sa.Enum('ICO', 'STO', name='offering_type', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_supply > 0', name='ck_launched_tokens_supply_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index('ix_launched_tokens_creator', 'launched_tokens', ['creator_id'], unique=False)
    op.create_table('token_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_asset_id', sa.Integer(), nullable=False),
    sa.Column('offering_type', sa.Enum('ICO', 'STO', name='offering_type', native_enum=False, length=32), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('tokens_for_sale', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('hard_cap', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('soft_cap', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('raised', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('tokens_sold', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LIVE', 'SUCCESS', 'FAILED', 'CLOSED', name='offering_status', native_enum=False, length=32), nullable=False),
    sa.Column('requires_whitelist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('lockup_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sale_price > 0 AND tokens_for_sale > 0 AND hard_cap > 0 AND soft_cap >= 0 AND soft_cap <= hard_cap', name='ck_token_offerings_positive'),
    sa.ForeignKeyConstraint(['token_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_offerings_status', 'token_offerings', ['status'], unique=False)
    op.create_table('investor_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['token_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'user_id', name='uq_investor_whitelist')
    )
    op.create_table('lp_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['amm_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'user_id', name='uq_lp_positions')
    )
    op.create_table('sale_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('usdt_paid', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('tokens_bought', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('refunded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['token_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_purchases_offering', 'sale_purchases', ['offering_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_purchases_offering', table_name='sale_purchases')
    op.drop_table('sale_purchases')
    op.drop_table('lp_positions')
    op.drop_table('investor_whitelist')
    op.drop_index('ix_token_offerings_status', table_name='token_offerings')
    op.drop_table('token_offerings')
    op.drop_index('ix_launched_tokens_creator', table_name='launched_tokens')
    op.drop_table('launched_tokens')
    op.drop_table('amm_pools')
    # ### end Alembic commands ###
