"""wallet: assets, chains, ledger

Revision ID: 30992cd9ed1b
Revises: d2893adb5ae2
Create Date: 2026-07-22 13:18:56.309546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30992cd9ed1b'
down_revision: Union[str, None] = 'd2893adb5ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('CRYPTO', 'FIAT', name='asset_kind', native_enum=False, length=32), nullable=False),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scale >= 0 AND scale <= 18', name='ck_assets_scale_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('family', sa.Enum('EVM', 'TRON', 'UTXO', 'SOLANA', name='chain_family', native_enum=False, length=32), nullable=False),
    sa.Column('evm_chain_id', sa.Integer(), nullable=True),
    sa.Column('native_asset_symbol', sa.String(length=16), nullable=False),
    sa.Column('address_model', sa.Enum('PER_USER', 'SHARED_MEMO', name='address_model', native_enum=False, length=32), nullable=False),
    sa.Column('explorer_tx_url', sa.String(length=255), nullable=True),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(family = 'EVM' AND evm_chain_id IS NOT NULL) OR (family <> 'EVM' AND evm_chain_id IS NULL)", name='ck_chains_evm_chain_id_iff_evm'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('evm_chain_id', name='uq_chains_evm_chain_id')
    )
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'ORDER_LOCK', 'ORDER_UNLOCK', 'TRADE', 'FEE', 'TDS', 'ADJUSTMENT', 'ADMIN_CREDIT', name='transaction_kind', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_ledger_transactions_kind', 'ledger_transactions', ['kind', 'created_at'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('AVAILABLE', 'LOCKED', 'EXTERNAL', 'FEE_INCOME', 'TDS_PAYABLE', name='account_type', native_enum=False, length=32), nullable=False),
    sa.Column('balance', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(account_type IN ('AVAILABLE', 'LOCKED') AND user_id IS NOT NULL) OR (account_type NOT IN ('AVAILABLE', 'LOCKED') AND user_id IS NULL)", name='ck_accounts_user_type_consistency'),
    sa.CheckConstraint("balance >= 0 OR account_type IN ('EXTERNAL', 'TDS_PAYABLE')", name='ck_accounts_no_negative_user_balance'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_accounts_system_asset_type', 'accounts', ['asset_id', 'account_type'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('uq_accounts_user_asset_type', 'accounts', ['user_id', 'asset_id', 'account_type'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('asset_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=128), nullable=True),
    sa.Column('onchain_decimals', sa.Integer(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('confirmations_large', sa.Integer(), nullable=False),
    sa.Column('large_threshold', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('min_deposit', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('min_withdrawal', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('withdrawal_fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('deposit_enabled', sa.Boolean(), nullable=False),
    sa.Column('withdraw_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confirmations >= 0 AND confirmations_large >= confirmations', name='ck_asset_networks_confirmations_ordered'),
    sa.CheckConstraint('min_deposit >= 0 AND min_withdrawal >= 0 AND withdrawal_fee >= 0', name='ck_asset_networks_non_negative_amounts'),
    sa.CheckConstraint('onchain_decimals >= 0 AND onchain_decimals <= 18', name='ck_asset_networks_decimals_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'chain_id', name='uq_asset_networks_asset_chain')
    )
    op.create_index('uq_asset_networks_chain_contract', 'asset_networks', ['chain_id', 'contract_address'], unique=True, postgresql_where=sa.text('contract_address IS NOT NULL'))
    op.create_index('uq_asset_networks_chain_native', 'asset_networks', ['chain_id'], unique=True, postgresql_where=sa.text('contract_address IS NULL'))
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name='ck_ledger_entries_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'account_id', name='uq_ledger_entries_txn_account')
    )
    op.create_index('ix_ledger_entries_account', 'ledger_entries', ['account_id', 'id'], unique=False)
    op.create_index('ix_ledger_entries_transaction', 'ledger_entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###

    # --- hand-written: the invariants that make this a ledger, and a chain-decimals guard ----

    # (a) assets.scale must cover every network's on-chain decimals. A CHECK cannot span two
    #     tables, so it is a trigger, enforced from both sides. USDT is 6 decimals on most chains
    #     but 18 on BSC: list it against a scale-8 asset and every BSC deposit either fails or
    #     silently rounds the remainder into our pocket.
    op.execute(
        """
        CREATE FUNCTION assert_network_decimals_fit_asset_scale() RETURNS trigger AS $$
        DECLARE asset_scale integer; asset_symbol text;
        BEGIN
            SELECT scale, symbol INTO asset_scale, asset_symbol FROM assets WHERE id = NEW.asset_id;
            IF asset_scale < NEW.onchain_decimals THEN
                RAISE EXCEPTION
                    'asset % has ledger scale % but this network needs % on-chain decimals',
                    asset_symbol, asset_scale, NEW.onchain_decimals;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE FUNCTION assert_asset_scale_fits_networks() RETURNS trigger AS $$
        DECLARE worst integer;
        BEGIN
            SELECT MAX(onchain_decimals) INTO worst FROM asset_networks WHERE asset_id = NEW.id;
            IF worst IS NOT NULL AND NEW.scale < worst THEN
                RAISE EXCEPTION 'cannot lower scale of % to %: a network needs % decimals',
                    NEW.symbol, NEW.scale, worst;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_network_decimals_fit_asset_scale"
        " BEFORE INSERT OR UPDATE OF asset_id, onchain_decimals ON asset_networks"
        " FOR EACH ROW EXECUTE FUNCTION assert_network_decimals_fit_asset_scale();"
    )
    op.execute(
        "CREATE TRIGGER trg_asset_scale_fits_networks"
        " BEFORE UPDATE OF scale ON assets"
        " FOR EACH ROW EXECUTE FUNCTION assert_asset_scale_fits_networks();"
    )

    # (b) Ledger entries are append-only. A ledger whose history can be edited no longer
    #     describes what happened. A speed bump, not a boundary (the table owner can drop it),
    #     but it closes the accidental case — a careless migration, an ORM cascade.
    op.execute(
        """
        CREATE FUNCTION reject_ledger_entry_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ledger_entries is append-only; % is not permitted. '
                'Post a compensating transaction instead.', TG_OP;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_ledger_entries_append_only"
        " BEFORE UPDATE OR DELETE ON ledger_entries"
        " FOR EACH ROW EXECUTE FUNCTION reject_ledger_entry_mutation();"
    )

    # (c) An entry's asset must match its account's asset — else a BTC amount against a USDT
    #     account still balances per asset_id while the account's balance becomes meaningless.
    op.execute(
        """
        CREATE FUNCTION assert_entry_asset_matches_account() RETURNS trigger AS $$
        DECLARE account_asset integer;
        BEGIN
            SELECT asset_id INTO account_asset FROM accounts WHERE id = NEW.account_id;
            IF account_asset <> NEW.asset_id THEN
                RAISE EXCEPTION 'entry asset % does not match account % holding asset %',
                    NEW.asset_id, NEW.account_id, account_asset;
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_ledger_entry_asset_matches_account"
        " BEFORE INSERT ON ledger_entries"
        " FOR EACH ROW EXECUTE FUNCTION assert_entry_asset_matches_account();"
    )

    # (d) THE invariant: every transaction sums to zero, per asset. A DEFERRED constraint
    #     trigger, because entries are inserted one at a time and the sum is only meaningful once
    #     the transaction is complete. Deferring to commit is what makes it both correct and
    #     impossible to route around — an application check is neither.
    op.execute(
        """
        CREATE FUNCTION assert_ledger_transaction_balances() RETURNS trigger AS $$
        DECLARE unbalanced RECORD;
        BEGIN
            SELECT asset_id, SUM(amount) AS total INTO unbalanced
            FROM ledger_entries WHERE transaction_id = NEW.transaction_id
            GROUP BY asset_id HAVING SUM(amount) <> 0 LIMIT 1;
            IF FOUND THEN
                RAISE EXCEPTION 'ledger transaction % does not balance: asset % sums to %',
                    NEW.transaction_id, unbalanced.asset_id, unbalanced.total;
            END IF;
            RETURN NULL;
        END; $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER trg_ledger_transaction_balances"
        " AFTER INSERT ON ledger_entries"
        " DEFERRABLE INITIALLY DEFERRED"
        " FOR EACH ROW EXECUTE FUNCTION assert_ledger_transaction_balances();"
    )


def downgrade() -> None:
    for stmt in (
        "DROP TRIGGER IF EXISTS trg_ledger_transaction_balances ON ledger_entries",
        "DROP TRIGGER IF EXISTS trg_ledger_entry_asset_matches_account ON ledger_entries",
        "DROP TRIGGER IF EXISTS trg_ledger_entries_append_only ON ledger_entries",
        "DROP TRIGGER IF EXISTS trg_asset_scale_fits_networks ON assets",
        "DROP TRIGGER IF EXISTS trg_network_decimals_fit_asset_scale ON asset_networks",
        "DROP FUNCTION IF EXISTS assert_ledger_transaction_balances()",
        "DROP FUNCTION IF EXISTS assert_entry_asset_matches_account()",
        "DROP FUNCTION IF EXISTS reject_ledger_entry_mutation()",
        "DROP FUNCTION IF EXISTS assert_asset_scale_fits_networks()",
        "DROP FUNCTION IF EXISTS assert_network_decimals_fit_asset_scale()",
    ):
        op.execute(stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_entries_transaction', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_account', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('uq_asset_networks_chain_native', table_name='asset_networks', postgresql_where=sa.text('contract_address IS NULL'))
    op.drop_index('uq_asset_networks_chain_contract', table_name='asset_networks', postgresql_where=sa.text('contract_address IS NOT NULL'))
    op.drop_table('asset_networks')
    op.drop_index('uq_accounts_user_asset_type', table_name='accounts', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_accounts_system_asset_type', table_name='accounts', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_table('accounts')
    op.drop_index('ix_ledger_transactions_kind', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_table('chains')
    op.drop_table('assets')
    # ### end Alembic commands ###
