"""p2p ads and orders

Revision ID: 339788d51854
Revises: 87ca5ba219d7
Create Date: 2026-07-28 12:12:29.924706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339788d51854'
down_revision: Union[str, None] = '87ca5ba219d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p2p_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='p2p_side', native_enum=False, length=32), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('fiat', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('min_fiat', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('max_fiat', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('available_qty', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('payment_methods', sa.String(length=256), nullable=False),
    sa.Column('terms', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CLOSED', name='p2p_ad_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_qty >= 0', name='ck_p2p_ads_qty_nonneg'),
    sa.CheckConstraint('min_fiat > 0 AND max_fiat >= min_fiat', name='ck_p2p_ads_limits'),
    sa.CheckConstraint('price > 0', name='ck_p2p_ads_price_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_p2p_ads_browse', 'p2p_ads', ['asset_id', 'fiat', 'side', 'status'], unique=False)
    op.create_index('ix_p2p_ads_maker', 'p2p_ads', ['maker_id'], unique=False)
    op.create_table('p2p_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('maker_id', sa.BigInteger(), nullable=False),
    sa.Column('taker_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('fiat', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('crypto_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fiat_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'RELEASED', 'CANCELED', 'DISPUTED', name='p2p_order_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('crypto_amount > 0 AND fiat_amount > 0 AND price > 0', name='ck_p2p_orders_positive'),
    sa.CheckConstraint('seller_id <> buyer_id', name='ck_p2p_orders_distinct_parties'),
    sa.ForeignKeyConstraint(['ad_id'], ['p2p_ads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_p2p_orders_ad', 'p2p_orders', ['ad_id'], unique=False)
    op.create_index('ix_p2p_orders_maker', 'p2p_orders', ['maker_id', 'id'], unique=False)
    op.create_index('ix_p2p_orders_taker', 'p2p_orders', ['taker_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_p2p_orders_taker', table_name='p2p_orders')
    op.drop_index('ix_p2p_orders_maker', table_name='p2p_orders')
    op.drop_index('ix_p2p_orders_ad', table_name='p2p_orders')
    op.drop_table('p2p_orders')
    op.drop_index('ix_p2p_ads_maker', table_name='p2p_ads')
    op.drop_index('ix_p2p_ads_browse', table_name='p2p_ads')
    op.drop_table('p2p_ads')
    # ### end Alembic commands ###
