"""futures positions

Revision ID: 4a7fb3c995db
Revises: 4d083692274f
Create Date: 2026-07-31 14:07:52.575566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7fb3c995db'
down_revision: Union[str, None] = '4d083692274f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='position_side', native_enum=False, length=32), nullable=False),
    sa.Column('size', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('margin', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LIQUIDATED', name='position_status', native_enum=False, length=32), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('size > 0 AND entry_price > 0 AND leverage >= 1 AND margin >= 0', name='ck_futures_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_futures_open', 'futures_positions', ['status', 'symbol'], unique=False)
    op.create_index('ix_futures_user', 'futures_positions', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###

    # Let the futures insurance pool go negative, alongside the other system liabilities.
    op.drop_constraint("ck_accounts_no_negative_user_balance", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_no_negative_user_balance", "accounts",
        "balance >= 0 OR account_type IN ('EXTERNAL', 'TDS_PAYABLE', 'MARGIN_BORROWED', 'FUTURES_INSURANCE')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_accounts_no_negative_user_balance", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_no_negative_user_balance", "accounts",
        "balance >= 0 OR account_type IN ('EXTERNAL', 'TDS_PAYABLE', 'MARGIN_BORROWED')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_futures_user', table_name='futures_positions')
    op.drop_index('ix_futures_open', table_name='futures_positions')
    op.drop_table('futures_positions')
    # ### end Alembic commands ###
