"""user parent_user_id

Revision ID: 4d083692274f
Revises: 9f44fd266294
Create Date: 2026-07-30 17:22:05.595587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d083692274f'
down_revision: Union[str, None] = '9f44fd266294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_parent_user_id'), 'users', ['parent_user_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['parent_user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_parent_user_id'), table_name='users')
    op.drop_column('users', 'parent_user_id')
    # ### end Alembic commands ###
