"""futures_positions table

Revision ID: 4eebb056dc63
Revises: 92d36704b2cb
Create Date: 2026-07-30 15:25:58.378168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eebb056dc63'
down_revision: Union[str, None] = '92d36704b2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='position_side', native_enum=False, length=32), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('size', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('margin', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LIQUIDATED', name='position_status', native_enum=False, length=32), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('leverage >= 1', name='ck_futures_positions_leverage'),
    sa.CheckConstraint('size >= 0 AND margin >= 0', name='ck_futures_positions_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_futures_positions_open', 'futures_positions', ['status', 'symbol'], unique=False)
    op.create_index('ix_futures_positions_user', 'futures_positions', ['user_id', 'status'], unique=False)
    op.create_index('uq_futures_open_position', 'futures_positions', ['user_id', 'symbol'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_futures_open_position', table_name='futures_positions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_futures_positions_user', table_name='futures_positions')
    op.drop_index('ix_futures_positions_open', table_name='futures_positions')
    op.drop_table('futures_positions')
    # ### end Alembic commands ###
