"""referrals + referral code

Revision ID: 64edb7a8e32d
Revises: 92d36704b2cb
Create Date: 2026-07-30 15:56:48.545375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64edb7a8e32d'
down_revision: Union[str, None] = '92d36704b2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referee_id', sa.BigInteger(), nullable=False),
    sa.Column('earned_usd', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id'),
    sa.UniqueConstraint('referee_id', name='uq_referrals_referee')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.add_column('users', sa.Column('referral_code', sa.String(length=12), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referral_code')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
