"""add orders table

Revision ID: 81dca55a1579
Revises: 0c6bb817d209
Create Date: 2026-07-23 13:58:23.212778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dca55a1579'
down_revision: Union[str, None] = '0c6bb817d209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_order_side'),
    sa.CheckConstraint('price > 0', name='ck_order_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_order_quantity_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('ix_orders_pair_status', 'orders', ['pair', 'status'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_pair_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
