"""order wallet column

Revision ID: 8437667c4809
Revises: 252e82ce6616
Create Date: 2026-07-28 15:50:38.825490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8437667c4809'
down_revision: Union[str, None] = '252e82ce6616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('wallet', sa.String(length=24), server_default='SPOT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'wallet')
    # ### end Alembic commands ###
