"""oco group id

Revision ID: 87ca5ba219d7
Revises: 10245424834f
Create Date: 2026-07-23 16:38:58.236136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ca5ba219d7'
down_revision: Union[str, None] = '10245424834f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('oco_group_id', sa.Integer(), nullable=True))
    op.create_index('ix_orders_oco', 'orders', ['oco_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_oco', table_name='orders')
    op.drop_column('orders', 'oco_group_id')
    # ### end Alembic commands ###
