"""kyc documents

Revision ID: 92d36704b2cb
Revises: 192e61f1a623
Create Date: 2026-07-30 12:58:12.097826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d36704b2cb'
down_revision: Union[str, None] = '192e61f1a623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_applications', sa.Column('doc_front', sa.Text(), nullable=True))
    op.add_column('kyc_applications', sa.Column('doc_back', sa.Text(), nullable=True))
    op.add_column('kyc_applications', sa.Column('selfie', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_applications', 'selfie')
    op.drop_column('kyc_applications', 'doc_back')
    op.drop_column('kyc_applications', 'doc_front')
    # ### end Alembic commands ###
