"""trading: markets, orders, trades

Revision ID: a798c4ddfeb9
Revises: ac774c6b9732
Create Date: 2026-07-22 17:16:28.251615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a798c4ddfeb9'
down_revision: Union[str, None] = 'ac774c6b9732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset_id', sa.Integer(), nullable=False),
    sa.Column('price_tick', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('qty_step', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('maker_fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('taker_fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_asset_id <> quote_asset_id', name='ck_markets_distinct_assets'),
    sa.CheckConstraint('price_tick > 0 AND qty_step > 0 AND min_notional >= 0', name='ck_markets_positive_filters'),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side', native_enum=False, length=32), nullable=False),
    sa.Column('type', sa.Enum('LIMIT', 'MARKET', name='order_type', native_enum=False, length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'REJECTED', name='order_status', native_enum=False, length=32), nullable=False),
    sa.Column('locked_asset_id', sa.Integer(), nullable=True),
    sa.Column('locked_remaining', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'MARKET') OR (price IS NOT NULL AND price > 0)", name='ck_orders_limit_has_price'),
    sa.CheckConstraint('filled_quantity >= 0 AND filled_quantity <= quantity', name='ck_orders_filled_range'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['locked_asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_book', 'orders', ['market_id', 'status', 'side', 'price', 'id'], unique=False)
    op.create_index('ix_orders_user', 'orders', ['user_id', 'id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('maker_order_id', sa.Integer(), nullable=False),
    sa.Column('taker_order_id', sa.Integer(), nullable=False),
    sa.Column('taker_side', sa.Enum('BUY', 'SELL', name='trade_taker_side', native_enum=False, length=32), nullable=False),
    sa.Column('ledger_txn_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0 AND quantity > 0', name='ck_trades_positive'),
    sa.ForeignKeyConstraint(['ledger_txn_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_market', 'trades', ['market_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_market', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_orders_user', table_name='orders')
    op.drop_index('ix_orders_book', table_name='orders')
    op.drop_table('orders')
    op.drop_table('markets')
    # ### end Alembic commands ###
