"""futures inverse coin-m

Revision ID: a969c318ef6d
Revises: 0b00be905952
Create Date: 2026-08-01 12:13:06.572948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a969c318ef6d'
down_revision: Union[str, None] = '0b00be905952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('futures_positions', sa.Column('inverse', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('futures_positions', sa.Column('margin_asset', sa.String(length=12), server_default='USDT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('futures_positions', 'margin_asset')
    op.drop_column('futures_positions', 'inverse')
    # ### end Alembic commands ###
