"""user role

Revision ID: ac774c6b9732
Revises: e992342e6108
Create Date: 2026-07-22 13:52:29.121938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac774c6b9732'
down_revision: Union[str, None] = 'e992342e6108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, which autogenerate omits: the table already has rows, and a NOT NULL column
    # with no default cannot be added to a non-empty table. Defaulting to the least privilege
    # (USER) is also the right way round — any row we forgot about is a user, not an admin.
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False, length=16), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
