"""wallet flow: deposit addresses, deposits, withdrawals, pending_withdrawal

Revision ID: e992342e6108
Revises: 30992cd9ed1b
Create Date: 2026-07-22 13:43:32.290405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e992342e6108'
down_revision: Union[str, None] = '30992cd9ed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_network_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('memo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_network_id'], ['asset_networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_network_id', name='uq_deposit_addresses_user_network')
    )
    op.create_index('ix_deposit_addresses_lookup', 'deposit_addresses', ['asset_network_id', 'address'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_network_id', sa.Integer(), nullable=False),
    sa.Column('to_address', sa.String(length=128), nullable=False),
    sa.Column('memo', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BROADCAST', 'CONFIRMED', 'FAILED', 'CANCELED', name='withdrawal_status', native_enum=False, length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('reserve_txn_id', sa.Integer(), nullable=True),
    sa.Column('settle_txn_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0 AND fee >= 0', name='ck_withdrawals_amounts'),
    sa.ForeignKeyConstraint(['asset_network_id'], ['asset_networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reserve_txn_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settle_txn_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_withdrawals_idempotency_key')
    )
    op.create_index('ix_withdrawals_status', 'withdrawals', ['status'], unique=False)
    op.create_index('ix_withdrawals_user', 'withdrawals', ['user_id', 'id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_network_id', sa.Integer(), nullable=False),
    sa.Column('deposit_address_id', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'CREDITED', 'ORPHANED', name='deposit_status', native_enum=False, length=32), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('required_confirmations', sa.Integer(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('block_hash', sa.String(length=128), nullable=True),
    sa.Column('ledger_txn_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_deposits_amount_positive'),
    sa.ForeignKeyConstraint(['asset_network_id'], ['asset_networks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deposit_address_id'], ['deposit_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledger_txn_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_network_id', 'tx_hash', 'vout', name='uq_deposits_txid')
    )
    op.create_index('ix_deposits_status', 'deposits', ['status'], unique=False)
    op.create_index('ix_deposits_user', 'deposits', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: PENDING_WITHDRAWAL is a new user account type, so the consistency check must
    # admit it as user-owned. Autogenerate does not diff CHECK constraint text, so this is manual.
    op.drop_constraint("ck_accounts_user_type_consistency", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_user_type_consistency",
        "accounts",
        "(account_type IN ('AVAILABLE', 'LOCKED', 'PENDING_WITHDRAWAL') AND user_id IS NOT NULL)"
        " OR (account_type NOT IN ('AVAILABLE', 'LOCKED', 'PENDING_WITHDRAWAL') AND user_id IS NULL)",
    )


def downgrade() -> None:
    op.drop_constraint("ck_accounts_user_type_consistency", "accounts", type_="check")
    op.create_check_constraint(
        "ck_accounts_user_type_consistency",
        "accounts",
        "(account_type IN ('AVAILABLE', 'LOCKED') AND user_id IS NOT NULL)"
        " OR (account_type NOT IN ('AVAILABLE', 'LOCKED') AND user_id IS NULL)",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deposits_user', table_name='deposits')
    op.drop_index('ix_deposits_status', table_name='deposits')
    op.drop_table('deposits')
    op.drop_index('ix_withdrawals_user', table_name='withdrawals')
    op.drop_index('ix_withdrawals_status', table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index('ix_deposit_addresses_lookup', table_name='deposit_addresses')
    op.drop_table('deposit_addresses')
    # ### end Alembic commands ###
