"""asset custodial flag

Revision ID: f5664f09a690
Revises: a798c4ddfeb9
Create Date: 2026-07-23 12:38:27.385907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5664f09a690'
down_revision: Union[str, None] = 'a798c4ddfeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default true: existing seeded assets are all custodial (they have networks).
    op.add_column('assets', sa.Column('custodial', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'custodial')
    # ### end Alembic commands ###
